kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ include "webapp.fullname" . }} 
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  buildVersion: {{ .Values.buildVersion | b64enc }}
